
FROM	python:3.12-slim-bookworm
COPY	/uv/uvx	/bin/
ENV	UV_SYSTEM_PYTHON	1
ENV	UV_CACHE_DIR	/opt/uv-cache
ENV	UV_COMPILE_BYTECODE	1
WORKDIR	/app
COPY	pyproject.toml	requirements.txt	./
RUN	uv pip install --system -r requirements.txt
COPY	src/	./src/
COPY	.python-version	./.python-version
RUN	mkdir -p /app/ramayana
EXPOSE	8000
CMD	["uvicorn","src.main:app","--host","0.0.0.0","--port","8000"]
