[project]
name = "ramayana-tagging-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[all]>=0.115.12",
    "loguru>=0.7.3",
    "motor>=3.7.0",
    "python-dotenv>=1.1.0",
]
